/**
 * Machine-readable error codes for API consumers.
 * Use these with AppError's `code` parameter for stable, parseable error responses.
 *
 * Convention: SCREAMING_SNAKE_CASE, grouped by domain.
 */
export const ErrorCodes = {
  // Auth
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Authorization
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Validation
  INVALID_INPUT: "INVALID_INPUT",
  UNSUPPORTED_CURRENCY: "UNSUPPORTED_CURRENCY",

  // Products
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  PRODUCT_INACTIVE: "PRODUCT_INACTIVE",

  // Cart
  CART_NOT_FOUND: "CART_NOT_FOUND",
  CART_EMPTY: "CART_EMPTY",

  // Orders
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_NOT_COMPLETABLE: "ORDER_NOT_COMPLETABLE",
  ORDER_ALREADY_COMPLETED: "ORDER_ALREADY_COMPLETED",

  // Payments
  CARD_DECLINED: "CARD_DECLINED",
  STRIPE_UNAVAILABLE: "STRIPE_UNAVAILABLE",
  STRIPE_INVALID_REQUEST: "STRIPE_INVALID_REQUEST",
  INSUFFICIENT_WALLET_BALANCE: "INSUFFICIENT_WALLET_BALANCE",

  // Promos
  PROMO_NOT_FOUND: "PROMO_NOT_FOUND",
  PROMO_EXPIRED: "PROMO_EXPIRED",
  PROMO_ALREADY_REDEEMED: "PROMO_ALREADY_REDEEMED",
  PROMO_LIMIT_REACHED: "PROMO_LIMIT_REACHED",

  // Reviews
  DUPLICATE_REVIEW: "DUPLICATE_REVIEW",
  INVALID_RATING: "INVALID_RATING",

  // Vendors
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  VENDOR_NOT_VERIFIED: "VENDOR_NOT_VERIFIED",
  VENDOR_SUSPENDED: "VENDOR_SUSPENDED",

  // Payouts
  PAYOUT_INSUFFICIENT_BALANCE: "PAYOUT_INSUFFICIENT_BALANCE",
  PAYOUT_ALREADY_PROCESSED: "PAYOUT_ALREADY_PROCESSED",

  // General
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
